version: 2.1

jobs:
  blint:
    machine: true
    steps:
      - checkout
      - run:
          name: "Shell Lint"
          command: |
              ls -lrt
workflows:
  version: 2.1
  
  Bot-shell-lint:
    jobs:
      - blint:
          filters:
            changes:
              only: 'functions'
