version: 2.1

jobs:
  shell-lint:
    machine: true
    steps:
      - checkout
      - run:
          name: "Shell Lint"
          command: |
              ls -lrt
  filters:
    branches:
      only:
        - dev-v3   
