version: 2.1

jobs:
  blint:
    machine: true
    steps:
      - checkout
      - run:
          name: "Shell Lint"
          command: |
              echo "[$(cat functions/*.sh | grep -E "^[a-z].*\(\)" | cut -d'(' -f1 | wc -l) functions]"
workflows:
  version: 2.1
  
  Bot-shell-lint:
    jobs:
      - blint:
          filters:
            branches:
              only: dev-v3
