version: 2.1

jobs:
  blint:
    machine: true
    steps:
      - checkout
      - run:
          name: "Shell Lint"
          command: |
              echo "[$(cat functions/*.sh | grep -E "^[a-z].*\(\)" | cut -d'(' -f1 | wc -l) function(s) found]"
              echo "Trying to test example function 'helper.random'..."
              source functions/helper.random
              echo "random number between 0 and 999: $(helper.random 999)"
workflows:
  version: 2.1
  
  Bot-shell-lint:
    jobs:
      - blint:
          filters:
            branches:
              only: dev-v3
