version: 2.1

jobs:
  blint:
    machine: true
    steps:
      - checkout
      - run:
          name: "Shell Lint"
          command: |
              TELEGRAM_TOKEN="none"
              NOTIFICATION_IDS="none"
              BASEDIR="/home/circleci/project"
              echo "[$(cat ${BASEDIR}/functions/*.sh | grep -E "^[a-z].*\(\)" | cut -d'(' -f1 | wc -l) function(s) found]"
              echo "Trying to test example function 'helper.random'..."
              source ${BASEDIR}/functions/utils.sh
              helper.random 10
workflows:
  version: 2.1
  
  Bot-shell-lint:
    jobs:
      - blint:
          filters:
            branches:
              only: develop
