version 2.1

jobs:
  botlint:
    steps:
      - checkout
      - run:
          name: "Shell Lint"
          command: |
              ls -lrt
    filters:
      branches:
        only:
          - dev-v3   
